name: HACS Validation

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS Action
        uses: hacs/action@main
